jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ...
    - name: Deploy to Staging
      if: success()
      run: |
        docker pull rahuldss99/myapp-nextjs:latest
        docker-compose -f docker-compose.yml up -d
