name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: go mod tidy
    - name: Run tests
      run: go test ./...
    - name: Run linter
      run: golangci-lint run ./...
